Create footer section
aceDavon/Portfolio-project pull request #3
Opened 2022-07-05 19:09 UTC by aceDavon

Collaboration work was done on the footer section of my portfolio alongside my coding partner.

2022-07-05 19:55 UTC, Nemwel-Boniface requested changes
## Hello @aceDavon     :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job setting your portfolio footer and contact form you have done a tremendous job :clap:  :clap:  
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] It appears that there is an overflow that makes your footer section to have a horizontal scroll. Kindly make sure that you stick as much as possible to the chosen Figma design in terms of colors, fonts etx.

**This is how your design currently looks like:**
![image](https://user-images.githubusercontent.com/86318284/177404328-18755960-2347-4890-844d-31a11f2dae30.png)


**This is the desired Figma design:**
![image](https://user-images.githubusercontent.com/86318284/177404453-03b8314d-3f39-485c-ad08-c29cec0d8151.png)





_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 19:55 UTC, Nemwel-Boniface commented on index.html
> +              <li><textarea name="message" required placeholder="Enter text Here"></textarea></li>
- [ ] Great job having some form validations in place. The only bit that is left according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md) is to give your text area a max length of 500. Kindly add it.

2022-07-05 19:55 UTC, Nemwel-Boniface commented on index.html
> +              <li><button class="btn btn-alt" type="submit">See Project</button></li>
- [ ] You have done a tremendous job styling your submit button. However, so that you stick as much as possible to the chosen Figma design, kindly make sure that you implement the button states eg on hover, on submit etc.This is the missing piece to perfection.

**Below are the desired button states**
![image](https://user-images.githubusercontent.com/86318284/177404823-23292c2f-e2bd-4247-8517-4cefba62eb07.png)

**It would also be a good thing to have the `cursor: pointer;` CSS rule to make it intuitive when your users try to submit  on your form**

2022-07-05 20:44 UTC, aceDavon commented on index.html
> +              <li><button class="btn btn-alt" type="submit">See Project</button></li>
@Nemwel-Boniface Thanks so much for your review. I styled all events on the buttons in one rule and applied the same class to similar buttons across my project.

2022-07-05 21:05 UTC, sumairq approved these changes
### Hi @aceDavon  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️professional README
✔️Correct Github flow
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 21:15 UTC, merged

2022-07-06 04:25 UTC, Nemwel-Boniface commented on index.html
> +              <li><button class="btn btn-alt" type="submit">See Project</button></li>
Hello @aceDavon I can see that you are learning really fast. Good job :clap: . The principle that you have just applied is called the DRY programming principle. If you are interested to learn further, have a look at [this awesome resource](https://www.itexico.com/blog/software-development-kiss-yagni-dry-3-principles-to-simplify-your-life).